language: R
sudo: false
cache: packages

matrix:
  include:
  - r: oldrel
  - r: release
  - r: devel

notifications:
  email: false

r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
